###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:5.7
      container_name: orcamento-pessoal-mysql
      working_dir: /application
      volumes:
        - ./phpdocker/mysql:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=db_orcamento_pessoal
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root
      ports:
        - "33060:3360"

    webserver:
      image: nginx:alpine
      container_name: orcamento-pessoal-webserver
      working_dir: /application
      volumes:
        - ./src:/application
        - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: orcamento-pessoal-php-fpm
      working_dir: /application
      volumes:
        - ./src:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini

